### ISSUE TITLE
Measurement/metric mappings and gauge grouping

### ISSUE THREAD

**Issue by lidkowiak** [davidB/metrics-influxdb#46]
Here https://github.com/iZettle/dropwizard-metrics-influxdb there is feature that tries to solve inconsistence between default dropwizard metrics naming and the InfluxDB time series model. I think it is complementary to transformation feature and it is worth to consider implementing these feature.

**Comment by davidB** [comment]
Hi,

Thanks for the link to dropwizard-metrics-influxdb.

I'll not work on this feature, because:

* I don't need it (tbh, I no longer use influxdb, so I keep the lib alive)
* I don't have lot of time to spend on the lib
* the spec/request need more details

But PR are a welcome (from you or someone else).

**Comment by rigalrock** [comment]
@davidB if possible , could  you please tell what else you are using instead of influxdb ?
